export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const SIGN_OUT = "SIGN_OUT";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const ROLES_LOADED = "ROLES_LOADED";
export const ROLES_LOADED_ERROR = "ROLES_LOADED_ERROR";
export const FOODS_LOADED = "FOODS_LOADED";
export const FOODS_LOADED_ERROR = "FOODS_LOADED_ERROR";
export const ADD_FOOD = "ADD_FOOD";
export const ADD_FOOD_ERROR = "ADD_FOOD_ERROR";
export const DELETE_FOOD = "DELETE_FOOD";
export const DELETE_FOOD_ERROR = "DELETE_FOOD_ERROR";
export const CHEMOTHERAPY_LOADED = "CHEMOTHERAPY_LOADED";
export const CHEMOTHERAPY_LOADED_ERROR = "CHEMOTHERAPY_LOADED_ERROR";
export const ADD_CHEMOTHERAPY = "ADD_CHEMOTHERAPY";
export const ADD_CHEMOTHERAPY_ERROR = "ADD_CHEMOTHERAPY_ERROR";
export const DELETE_CHEMOTHERAPY = "DELETE_CHEMOTHERAPY";
export const DELETE_CHEMOTHERAPY_ERROR = "DELETE_CHEMOTHERAPY_ERROR";
export const UPDATE_CHEMOTHERAPY = "UPDATE_CHEMOTHERAPY";
export const UPDATE_CHEMOTHERAPY_ERROR = "UPDATE_CHEMOTHERAPY_ERROR";
export const SIDE_EFFECTS_BY_USER_LOADED = "SIDE_EFFECTS_BY_USER_LOADED";
export const SIDE_EFFECTS_BY_ADMIN_LOADED = "SIDE_EFFECTS_BY_ADMIN_LOADED";
export const SIDE_EFFECTS_BY_USER_LOADED_ERROR =
  "SIDE_EFFECTS_BY_USER_LOADED_ERROR";
export const SIDE_EFFECTS_BY_ADMIN_LOADED_ERROR =
  "SIDE_EFFECTS_BY_ADMIN_LOADED_ERROR";
export const ADD_SIDE_EFFECT_BY_USER = "ADD_SIDE_EFFECT_BY_USER";
export const ADD_SIDE_EFFECT_BY_ADMIN = "ADD_SIDE_EFFECT_BY_ADMIN";
export const ADD_SIDE_EFFECT_BY_USER_ERROR = "ADD_SIDE_EFFECT_BY_USER_ERROR";
export const ADD_SIDE_EFFECT_BY_ADMIN_ERROR = "ADD_SIDE_EFFECT_BY_ADMIN_ERROR";
export const DELETE_SIDE_EFFECT_BY_USER = "DELETE_SIDE_EFFECT_BY_USER";
export const DELETE_SIDE_EFFECT_BY_ADMIN = "DELETE_SIDE_EFFECT_BY_ADMIN";
export const DELETE_SIDE_EFFECT_BY_USER_ERROR =
  "DELETE_SIDE_EFFECT_BY_USER_ERROR";
export const DELETE_SIDE_EFFECT_BY_ADMIN_ERROR =
  "DELETE_SIDE_EFFECT_BY_ADMIN_ERROR";
export const METHODS_OF_PREVENTION_LOADED = "METHODS_OF_PREVENTION_LOADED";
export const METHODS_OF_PREVENTION_LOADED_ERROR = "METHODS_OF_PREVENTION_LOADED_ERROR";
export const ADD_A_METHOD_OF_PREVENTION = "ADD_A_METHOD_OF_PREVENTION";
export const ADD_A_METHOD_OF_PREVENTION_ERROR = "ADD_A_METHOD_OF_PREVENTION_ERROR";
export const DELETE_A_METHOD_OF_PREVENTION = "DELETE_A_METHOD_OF_PREVENTION";
export const DELETE_A_METHOD_OF_PREVENTION_ERROR = "DELETE_A_METHOD_OF_PREVENTION_ERROR";
